# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-28 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('device', models.CharField(max_length=100, verbose_name='device')),
                ('record_dt', models.DateTimeField()),
                ('is_success', models.BooleanField()),
                ('spent_seconds', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['record_dt'],
            },
        ),
    ]
